version: '4'

services:
  mysql:
    image: mysql:8.1
    container_name: mysql_inventory_service
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

